/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ups.edu.compras;

import com.ups.edu.conexion.ConexionBD;
import com.ups.edu.ventas.model.Validacion;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Bravo
 */
public class Pruebas extends javax.swing.JFrame {

    /**
     * Creates new form Pruebas
     */
    
    Connection conn;
    DefaultTableModel modelo;
    public Pruebas() {
        initComponents();
        conn = ConexionBD.GetConnection();
        if(conn!=null){
            System.out.println("Conectado");
        }else{
            System.out.println("No conectado");
        }
        modelo = new DefaultTableModel();
        tableProductos.setModel(modelo);
        
        Object parametros[] = new Object[4];
        parametros[0]="Producto";
        parametros[1]="Marca";
        parametros[2]="Modelo";
        parametros[3]="Precio";

        for (int j = 0; j < parametros.length; j++) {
            modelo.addColumn(parametros[j]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        btnAgrega2Jtable = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        telefono1 = new javax.swing.JTextField();
        telefono2 = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        estado2 = new javax.swing.JRadioButton();
        estado1 = new javax.swing.JRadioButton();
        id_proveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnNuevoGuardar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(490, 400));

        jLabel10.setText("TIPO");

        jLabel11.setText("MARCA");

        jLabel12.setText("MODELO");

        jLabel13.setText("PRECIO UNITARIO");

        jLabel15.setText("DETALLE");

        txtDetalles.setColumns(20);
        txtDetalles.setRows(5);
        txtDetalles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDetallesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDetallesKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtDetalles);
        txtDetalles.setLineWrap(true);

        btnAgrega2Jtable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/anadir.png"))); // NOI18N
        btnAgrega2Jtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrega2JtableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTipo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgrega2Jtable, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgrega2Jtable))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        direccion.setEnabled(false);
        direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                direccionKeyPressed(evt);
            }
        });

        jLabel7.setText("TELEFONO");

        telefono1.setEnabled(false);
        telefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefono1KeyPressed(evt);
            }
        });

        telefono2.setEnabled(false);
        telefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefono2KeyPressed(evt);
            }
        });

        correo.setEnabled(false);
        correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                correoKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("PRODUCTOS");

        jLabel8.setText("CORREO");

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Marca", "Modelo", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProductos);

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/search.png"))); // NOI18N
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel4.setText("CIUDAD");

        txtCiudad.setEnabled(false);
        txtCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCiudadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCiudadKeyTyped(evt);
            }
        });

        jLabel1.setText("ID PROVEEDOR");

        buttonGroup1.add(estado2);
        estado2.setText("Inactivo");

        buttonGroup1.add(estado1);
        estado1.setText("Activo");
        estado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado1ActionPerformed(evt);
            }
        });

        id_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_proveedorActionPerformed(evt);
            }
        });
        id_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_proveedorKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("INFORMACION");

        jLabel3.setText("ESTADO");

        jLabel5.setText("NOMBRE");

        nombre.setEnabled(false);
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
        });

        jLabel6.setText("DIRECCION");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/cancelar_1.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/anadir.png"))); // NOI18N
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/borrar.png"))); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.setEnabled(false);

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/actualizar.png"))); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setEnabled(false);

        btnNuevoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/nuevousuario.png"))); // NOI18N
        btnNuevoGuardar.setText("NUEVO PROV.");
        btnNuevoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoGuardarActionPerformed(evt);
            }
        });

        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/sacar.png"))); // NOI18N
        btnQuitar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel8))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(direccion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(correo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                .addComponent(txtCiudad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estado1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(estado2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnQuitar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnNuevoGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estado1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estado2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuitar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionKeyPressed
        // TODO add your handling code here:
//        validar(evt, Validacion.NUMEROSLETRAS);
    }//GEN-LAST:event_direccionKeyPressed

    private void telefono1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono1KeyPressed
        // TODO add your handling code here:
//        validar(evt, Validacion.SOLONUMEROS);
    }//GEN-LAST:event_telefono1KeyPressed

    private void telefono2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono2KeyPressed
        // TODO add your handling code here:
//        validar(evt, Validacion.SOLONUMEROS);
    }//GEN-LAST:event_telefono2KeyPressed

    private void correoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoKeyPressed
        // TODO add your handling code here:
//        validar(evt, Validacion.CORREO);
    }//GEN-LAST:event_correoKeyPressed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        try{
            getProveedor(id_proveedor.getText());
        }catch(Exception e){

        }
    }//GEN-LAST:event_buscarActionPerformed

    private void txtCiudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudadKeyPressed
        // TODO add your handling code here:
        //validar(evt, Validacion.SOLOLETRAS);
    }//GEN-LAST:event_txtCiudadKeyPressed

    private void estado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estado1ActionPerformed

    private void id_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_proveedorActionPerformed

    private void id_proveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_proveedorKeyPressed
        // TODO add your handling code here:
        try{
//            validar(evt, Validacion.SOLONUMEROS);
            if(evt.getKeyCode() == 10){
                getProveedor(id_proveedor.getText());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe ingresar un valor en la caja de texto", "Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_id_proveedorKeyPressed

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed
        // TODO add your handling code here:
//        validar(evt, Validacion.SOLOLETRAS);
    }//GEN-LAST:event_nombreKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoGuardarActionPerformed
        // TODO add your handling code here:
        if(btnNuevoGuardar.getText().equals("NUEVO PROV.")){
            btnNuevoGuardar.setText("GUARDAR");
            btnNuevoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/guardar.jpg"))); // NOI18N
            activarCamposInsert();
        }else if(btnNuevoGuardar.getText().equals("GUARDAR")){
            desactivarCamposInsert();
            btnNuevoGuardar.setText("NUEVO PROV.");
            btnNuevoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/nuevousuario.png"))); // NOI18N
            boolean resultado = insertarProveedores();
            if(resultado){
                JOptionPane.showMessageDialog(this, "Dato ingresados correctamente","Información",JOptionPane.INFORMATION_MESSAGE);
            }else if(!resultado){
                JOptionPane.showMessageDialog(this, "Error en la inerción, formato incorrecto","Error",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnNuevoGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAgrega2JtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrega2JtableActionPerformed
        // TODO add your handling code here:
        agregarToTable();
    }//GEN-LAST:event_btnAgrega2JtableActionPerformed

    private void txtDetallesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDetallesKeyPressed
        // TODO add your handling code here:
        if(txtDetalles.getText().length() >= 50){
            evt.consume();
        }
    }//GEN-LAST:event_txtDetallesKeyPressed

    private void txtCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudadKeyTyped
        // TODO add your handling code here:
        if(isNumeric(String.valueOf(evt.getKeyChar()))){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtCiudadKeyTyped

    private void txtDetallesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDetallesKeyTyped
        // TODO add your handling code here:
        if(txtDetalles.getText().length() >= 50){
            evt.consume();
        }
    }//GEN-LAST:event_txtDetallesKeyTyped
    private boolean isNumeric(String a ){      
        try {
            Integer.parseInt(a);
            return true;
         }catch(NumberFormatException ex){
         
    
            return false;
        }
    }
    
    
    private void agregarToTable(){
        //DefaultTableModel modelo = new DefaultTableModel();
        int filas = modelo.getRowCount();
        System.out.println("Filas: "+filas);
//        tableProductos.setModel(modelo);
//        
//        Object parametros[] = new Object[4];
//        parametros[0]="Producto";
//        parametros[1]="Marca";
//        parametros[2]="Modelo";
//        parametros[3]="Precio";
//
//        for (int j = 0; j < parametros.length; j++) {
//            modelo.addColumn(parametros[j]);
//        }
        
        String datos [] = new String[4];
        datos[0] = txtTipo.getText();
        datos[1] = txtMarca.getText();
        datos[2] = txtModelo.getText();
        datos[3] = txtPrecio.getText();
        modelo.addRow(new Object[filas]);
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            modelo.setValueAt(datos[i], filas, i);
        }
        filas++;
    }
    
    private boolean insertarProveedores(){
        String insertaProveedores = "";
        String insertaProductos = "";
        try{
            if(consultarCiudad(txtCiudad.getText()) == false){
                insertarCiudad(txtCiudad.getText());
            }else{
                
            }
            
            return true;
        }catch(Exception e){
            System.out.println("Error en ingresar proveedor: "+e.getMessage());
            return false;
        }
    }
    
    private boolean consultarMarca(){
        try{
            String consultaMarca = "select `id_modelo` from `inv_Modelo_Producto` where `nombre`='"+txtMarca.getText()+"'";
            return true;
        }catch(Exception e){
            return false;
        }
    }
    private boolean consultarTipo(){
        String consultaTipo = "select `id_tipo` from `inv_Tipo_Producto` where `nombre`='"+txtTipo.getText()+"'";
        return true;
    }
    private boolean consultarModelo(){
        String consultaModelo = "select `id_marca` from `inv_Marca_Producto` where `nombre`='"+txtModelo.getText()+"'";
        return true;
    }
    
    private void insertarCiudad(String ciudad){
        try{
            String insertaCiudad = 
                    "INSERT INTO `cmprv_ciudad`(`descripcion`) VALUES (?)";
            CallableStatement call;
            call = conn.prepareCall(insertaCiudad);
            call.setString(1, ciudad);
            call.execute();
            call.close();
        }catch(Exception e){
            System.out.println("Error en insert: "+e.getMessage());
        }
    }
    
    private boolean consultarCiudad(String ciudad){
        int resultado = 0;
        try{
            String consultarCiudad = 
                    "SELECT COUNT(`id_ciudad`) FROM `cmprv_ciudad` WHERE `descripcion` ='"+ciudad+"'";
            CallableStatement cs = conn.prepareCall(consultarCiudad);
            ResultSet rs = cs.executeQuery();
            while(rs.next()){
                resultado = rs.getInt(1);
            }
            return resultado == 1;
        }catch(Exception e){
            System.out.println("Error en consulta: "+e.getMessage());
            return false;
        }
    }
    
    private void getProveedor(String cedula_proveedor){
        cambiarEstadoBotones();
        int i = 0;
        //DefaultTableModel modelo = new DefaultTableModel();
        String consultaProveedor = 
                "SELECT  `id_producto` , `id_ciudad` , `nombre`, `direccion` , `telefono1` , `telefono2` , `correo` , `estado` "
                + "FROM  `cmprv_provedores` where `cedula_proveedor` = '"+cedula_proveedor+"'";
        String consultaCiudad = "SELECT `descripcion` FROM `cmprv_ciudad` WHERE `id_ciudad` = ";
        String [] dataProveedorString = new String[5];
        Integer [] dataProveedorInt = new Integer[4];
        try{
            //tableProductos.setModel(modelo);
            CallableStatement cs = conn.prepareCall(consultaProveedor);
            ResultSet rs = cs.executeQuery();
            while(rs.next()){
                dataProveedorInt[0] = rs.getInt("id_producto");
                dataProveedorInt[1] = rs.getInt("id_ciudad");
                dataProveedorString[0] = rs.getString("nombre");
                dataProveedorString[1] = rs.getString("direccion");
                dataProveedorInt[2] = rs.getInt("telefono1");
                dataProveedorInt[3] = rs.getInt("telefono2");
                dataProveedorString[2] = rs.getString("correo");
                dataProveedorString[3] = rs.getString("estado");
            }
            
            consultaCiudad = consultaCiudad + dataProveedorInt[1];
            cs = conn.prepareCall(consultaCiudad);
            rs = cs.executeQuery();
            while(rs.next()){
                dataProveedorString[4] = rs.getString("descripcion");
            }
           
            String obtenerData = 
                    "SELECT invProducto.id_modelo, invProducto.id_marca, invProducto.id_tipo, invProducto.Precio_unitario" +
                    " FROM `inv_Producto` AS `invProducto`" +
                    " WHERE invProducto.id_producto ="+dataProveedorInt[0];   
            
            cs = conn.prepareCall(obtenerData);
            rs = cs.executeQuery();
            Integer data[] = new Integer[3];
            Double precio[] = new Double[1];
            while(rs.next()){
                
                i++;
                
                data[0] = rs.getInt("id_modelo");
                data[1] = rs.getInt("id_marca");
                data[2] = rs.getInt("id_tipo");
                precio[0] = rs.getDouble("Precio_unitario");
                
                Object datos[] = new Object[4];
                
                String consultaTipo = "select `nombre` from `inv_Tipo_Producto` where `id_tipo`="+data[2];
                String consultaModelo = "select `nombre` from `inv_Marca_Producto` where `id_marca`="+data[1];
                String consultaMarca = "select `nombre` from `inv_Modelo_Producto` where `id_modelo`="+data[0];

                cs = conn.prepareCall(consultaTipo);
                rs = cs.executeQuery();
                while(rs.next()){
                    datos[0] = rs.getObject("nombre");
                }

                cs = conn.prepareCall(consultaModelo);
                rs = cs.executeQuery();
                while(rs.next()){
                    datos[1] = rs.getObject("nombre");
                }

                cs = conn.prepareCall(consultaMarca);
                rs = cs.executeQuery();
                while(rs.next()){
                    datos[2] = rs.getObject("nombre");
                }
                datos[3] = precio[0];
                
//                Object parametros[] = new Object[4];
//                parametros[0]="Producto";
//                parametros[1]="Marca";
//                parametros[2]="Modelo";
//                parametros[3]="Precio";
//                
//                for (int j = 0; j < parametros.length; j++) {
//                    modelo.addColumn(parametros[j]);
//                }
                modelo.addRow(datos);
            }

            cs.close();
            rs.close();

            nombre.setText(dataProveedorString[0]);
            direccion.setText(dataProveedorString[1]);
            telefono1.setText(String.valueOf(dataProveedorInt[2]));
            telefono2.setText(String.valueOf(dataProveedorInt[3]));
            txtCiudad.setText(dataProveedorString[4]);
            correo.setText(dataProveedorString[2]);
            if(dataProveedorString[3].equals("A")){
                estado1.setSelected(true);
                estado2.setSelected(false);
            }else if(dataProveedorString[3].equals("I")){
                estado1.setSelected(false);
                estado2.setSelected(true);
            }
            
        }catch(Exception e){
//            Object parametros[] = new Object[4];
//            parametros[0]="Producto";
//            parametros[1]="Marca";
//            parametros[2]="Modelo";
//            parametros[3]="Precio";
//
//            for (int j = 0; j < parametros.length; j++) {
//                modelo.addColumn(parametros[j]);
//            }
            JOptionPane.showMessageDialog(this, "El proveedor a consultar no se encuentra registrado o el valor ingresado es nulo", "Error", JOptionPane.WARNING_MESSAGE);
            cambiarConError();
        }
    }
    
    public void validar(KeyEvent evt, String limite) {        
        //if(!(evt.getKeyCode()==8 || evt.getKeyCode()==37 || evt.getKeyCode()==39 ||evt.getKeyCode()==127)){
            if (!String.valueOf(evt.getKeyChar()).matches(limite)) {
                evt.consume();
            }             
        //}
        System.out.println("Tecla: "+evt.getKeyCode());
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pruebas().setVisible(true);
            }
        });
    }

    private void activarCamposInsert(){
        buscar.setEnabled(false);
        btnAgregar.setEnabled(true);
        btnQuitar.setEnabled(true);
        btnCancelar.setEnabled(true);
        
        nombre.setEnabled(true);
        direccion.setEnabled(true);
        telefono1.setEnabled(true);
        telefono2.setEnabled(true);
        txtCiudad.setEnabled(true);
        correo.setEnabled(true);
        estado1.setEnabled(true);
        estado2.setEnabled(true);
        
    }
    
    private void desactivarCamposInsert(){
        buscar.setEnabled(true);
        btnAgregar.setEnabled(false);
        btnQuitar.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        id_proveedor.setText("");
        nombre.setEnabled(false);nombre.setText("");
        direccion.setEnabled(false);direccion.setText("");
        telefono1.setEnabled(false);telefono1.setText("");
        telefono2.setEnabled(false);telefono2.setText("");
        txtCiudad.setEnabled(false);txtCiudad.setText("");
        correo.setEnabled(false);correo.setText("");
        estado1.setEnabled(false);estado1.setSelected(false);
        estado2.setEnabled(false);estado2.setSelected(false);
    }
    
    private void cancelar(){
        try{
            id_proveedor.setText("");
            nombre.setEnabled(false);nombre.setText("");
            direccion.setEnabled(false);direccion.setText("");
            telefono1.setEnabled(false);telefono1.setText("");
            telefono2.setEnabled(false);telefono2.setText("");
            txtCiudad.setEnabled(false);txtCiudad.setText("");
            correo.setEnabled(false);correo.setText("");
            estado1.setEnabled(false);estado1.setSelected(false);
            estado2.setEnabled(false);estado2.setSelected(false);

            while(modelo.getRowCount()>0){
                 modelo.removeRow(0);
            }

            if(btnNuevoGuardar.getText().equals("GUARDAR")){
                btnNuevoGuardar.setText("NUEVO PROV.");
                btnNuevoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/nuevousuario.png"))); // NOI18N
            }

            btnNuevoGuardar.setEnabled(true);
            eliminar.setEnabled(false);
            btnActualizar.setEnabled(false);
            btnAgregar.setEnabled(false);
            btnCancelar.setEnabled(false);
            buscar.setEnabled(true);
            btnQuitar.setEnabled(false);
        }catch(Exception E){
            id_proveedor.setText("");
            nombre.setEnabled(false);nombre.setText("");
            direccion.setEnabled(false);direccion.setText("");
            telefono1.setEnabled(false);telefono1.setText("");
            telefono2.setEnabled(false);telefono2.setText("");
            txtCiudad.setEnabled(false);txtCiudad.setText("");
            correo.setEnabled(false);correo.setText("");
            estado1.setEnabled(false);estado1.setSelected(false);
            estado2.setEnabled(false);estado2.setSelected(false);
            try{
                while(modelo.getRowCount()>0){
                    modelo.removeRow(0);
                }
            }catch(NullPointerException ex){}
            
            if(btnNuevoGuardar.getText().equals("GUARDAR")){
                btnNuevoGuardar.setText("NUEVO PROV.");
                btnNuevoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/compras/resources/nuevousuario.png"))); // NOI18N
            }

            btnNuevoGuardar.setEnabled(true);
            eliminar.setEnabled(false);
            btnActualizar.setEnabled(false);
            btnAgregar.setEnabled(false);
            btnCancelar.setEnabled(false);
            buscar.setEnabled(true);
            btnQuitar.setEnabled(false);
        }
    }
    
    private void cambiarEstadoBotones(){
        //Cambio en los botones cuando se trata de busquedas
        btnNuevoGuardar.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnCancelar.setEnabled(true);
        eliminar.setEnabled(true);
        btnActualizar.setEnabled(true);
        btnQuitar.setEnabled(false);
        //Cambio en las cajas de textos cuando se trata de busquedas
        nombre.setEnabled(true);
        direccion.setEnabled(true);
        telefono1.setEnabled(true);
        telefono2.setEnabled(true);
        txtCiudad.setEnabled(true);
        correo.setEnabled(true);
        estado1.setEnabled(true);
        estado2.setEnabled(true);
        tableProductos.setEnabled(true);
    }
    
    private void cambiarConError(){
        
        id_proveedor.setText("");
        
        telefono1.setText("");
        telefono2.setText("");
        
        modelo = new DefaultTableModel();
        //Cambio en los botones cuando se trata de busquedas
        btnNuevoGuardar.setEnabled(true);
        btnAgregar.setEnabled(false);
        btnCancelar.setEnabled(false);
        eliminar.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnQuitar.setEnabled(false);
        //Cambio en las cajas de textos cuando se trata de busquedas
        nombre.setEnabled(false);
        direccion.setEnabled(false);
        telefono1.setEnabled(false);
        telefono2.setEnabled(false);
        txtCiudad.setEnabled(false);
        correo.setEnabled(false);
        //tableProductos.setFocusable(false);
        estado1.setEnabled(false);
        estado2.setEnabled(false);
        tableProductos.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgrega2Jtable;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNuevoGuardar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton eliminar;
    private javax.swing.JRadioButton estado1;
    private javax.swing.JRadioButton estado2;
    private javax.swing.JTextField id_proveedor;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField telefono1;
    private javax.swing.JTextField telefono2;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextArea txtDetalles;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
