
package com.ups.edu.rrhh.menuinicio;
import com.ups.edu.conexion.ConexionBD;
import java.sql.*;
import javax.swing.JOptionPane;

public class Iframe3 extends javax.swing.JInternalFrame {
ConexionBD cc = new ConexionBD();
Connection cn= cc.GetConnection();
    /**
     * Creates new form Iframe3
     */
    public Iframe3() throws SQLException {
        initComponents();
        this.setVisible(true);
        int he = Integer.parseInt(txtHorasExtras.getText()); 
        int com = Integer.parseInt(txtComisiones.getText()); 
        int nhe = he * (6);
        jLabel9.setText(nhe+"");
        int categoria1 = (int) cmbSueldo.getSelectedItem();
        int z = nhe + categoria1 + com ;
        jLabel10.setText(z+"");
        dameCargo();
        dameSueldo();
        dameBanco();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidemp = new javax.swing.JTextField();
        cmbCargo = new javax.swing.JComboBox<>();
        cmbSueldo = new javax.swing.JComboBox<>();
        txtHorasExtras = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtComisiones = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmbBanco = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdRol = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Rol de Pago");

        jLabel1.setText("Codigo Empleado:");

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("ProduEntrega S.A.");

        jLabel3.setText("Cargo:");

        jLabel4.setText("Sueldo Básico:");

        jLabel5.setText("N° Horas Extras:");

        jLabel6.setText("Comisiones:");

        jLabel7.setText("Horas Extras:");

        jLabel8.setText("Total");

        txtidemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidempKeyTyped(evt);
            }
        });

        txtHorasExtras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasExtrasKeyTyped(evt);
            }
        });

        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtComisiones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComisionesKeyTyped(evt);
            }
        });

        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Banco:");

        jLabel12.setText("Rol n°:");

        txtIdRol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdRolKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHorasExtras, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(35, 35, 35))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbCargo, 0, 177, Short.MAX_VALUE)
                                    .addComponent(cmbSueldo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbBanco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtidemp, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIdRol)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(txtComisiones))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton1)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 113, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtIdRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHorasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if (txtIdRol.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "INGRESE CODIGO DE ROL DE PAGO","Error",JOptionPane.WARNING_MESSAGE);
        }else if (txtidemp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "INGRESE CODIGO PERSONAL","Error",JOptionPane.WARNING_MESSAGE);
        }else if (txtHorasExtras.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "INGRESE NUMERO DE HORAS EXTRAS","Error",JOptionPane.WARNING_MESSAGE);
        }else if (txtComisiones.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "INGRESE VALOR DE COMISIONES","Error",JOptionPane.WARNING_MESSAGE);
        }else{
            daoRol obj = new daoRol();
            Combo cb1 = (Combo) cmbCargo.getSelectedItem();
            int idcargo = cb1.getCodigo();
            Combo cb2 = (Combo) cmbSueldo.getSelectedItem();
            int idsueldo = cb2.getCodigo();
            Combo cb3 = (Combo) cmbBanco.getSelectedItem();
            int idbanco = cb3.getCodigo();
            int a = Integer.parseInt(txtIdRol.getText()); 
            int b = Integer.parseInt(txtidemp.getText()); 
            int c = Integer.parseInt(jLabel9.getText());
            int d = Integer.parseInt(txtComisiones.getText());
            int e = Integer.parseInt(jLabel10.getText());
           obj.Insertar(new roldepagos(a,b,idcargo,idsueldo,idbanco,c,d,e));
            txtIdRol.setText("");
            txtidemp.setText("");
            txtHorasExtras.setText("");
            txtComisiones.setText("");
               
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIdRolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdRolKeyTyped
        char car = evt.getKeyChar();
        if(txtIdRol.getText().length()>=10 ) evt.consume();
        if(( car<'0' || car>'9' )) evt.consume();
   // TODO add your handling code here:
    }//GEN-LAST:event_txtIdRolKeyTyped

    private void txtidempKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidempKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if(txtidemp.getText().length()>=10 ) evt.consume();
        if(( car<'0' || car>'9' )) evt.consume();
   
    }//GEN-LAST:event_txtidempKeyTyped

    private void txtHorasExtrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasExtrasKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if(txtHorasExtras.getText().length()>=2 ) evt.consume();
        if(( car<'0' || car>'9' )) evt.consume();
   
    }//GEN-LAST:event_txtHorasExtrasKeyTyped

    private void txtComisionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComisionesKeyTyped
        char car = evt.getKeyChar();
        if(txtHorasExtras.getText().length()>=3 ) evt.consume();
        if(( car<'0' || car>'9' )) evt.consume();
    }//GEN-LAST:event_txtComisionesKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBanco;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JComboBox<String> cmbSueldo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtComisiones;
    private javax.swing.JTextField txtHorasExtras;
    private javax.swing.JTextField txtIdRol;
    private javax.swing.JTextField txtidemp;
    // End of variables declaration//GEN-END:variables
private void dameCargo() throws SQLException {
        ConexionBD cn = new ConexionBD();
        Connection conn = cn.GetConnection();
        ResultSet rs;
        String sql = "SELECT nombre FROM rrhh_cargo";
        PreparedStatement sqls = conn.prepareStatement(sql);
        rs = sqls.executeQuery();
        while(rs.next()){
            cargo ca = new cargo();
            ca.setNombre(rs.getString("nombre"));
            cmbCargo.addItem(ca+"");
        }
    }
   
    private void dameSueldo() throws SQLException {
        ConexionBD cn = new ConexionBD();
        Connection conn = cn.GetConnection();
        ResultSet rs;
        String sql = "SELECT cantidad FROM rrhh_sueldo";
        PreparedStatement sqls = conn.prepareStatement(sql);
        rs = sqls.executeQuery();
        while(rs.next()){
            sueldo su = new sueldo();
           su.setCantidad(rs.getInt("cantidad"));
            cmbSueldo.addItem(rs.getInt("cantidad")+"");
        }
    }   
    private void dameBanco() throws SQLException {
        ConexionBD cn = new ConexionBD();
        Connection conn = cn.GetConnection();
        ResultSet rs;
        String sql = "SELECT nombre FROM rrhh_banco";
        PreparedStatement sqls = conn.prepareStatement(sql);
        rs = sqls.executeQuery();
        while(rs.next()){
            banco b = new banco();
            b.setNombre(rs.getString("nombre"));
            cmbBanco.addItem(b+"");
        }
    } 
}
