/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ups.edu.rrhh.menuinicio;

import Inventario_Otros_codigos.ConexionBD;
import com.ups.edu.ventas.views.*;
import com.ups.edu.inventario.*;
import static com.ups.edu.inventario.Principal1.rb_ingresos;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author SERVIDOR
 */
public class MenuInicio extends javax.swing.JFrame {
Connection conn = (Connection) ConexionBD.GetConnection();
    /**
     * Creates new form menu
     */
    
    private FrmVta_Ofertas frmVtaOferta = new FrmVta_Ofertas();
    private FrmVta_Factura frmVtaFactura;
    private FrmVta_Cliente frmVtaCliente = new FrmVta_Cliente();
    private FrmVta_Promocion frmVtaPromocion ;
    private FrmVta_Comisiones frmVtaComisones ;
    private FrmVta_FormaPago frmVtaPago;
    private FrmVta_Garantias frmVtaGarantia;
    
    public MenuInicio() {
        initComponents();
                jMFinanciero.setVisible(false);
                jMRecHum.setVisible(false);
                jMCompras.setVisible(false);
                jMVentas.setVisible(false);
                jMInventario.setVisible(false);
                
    frmVtaPromocion = new FrmVta_Promocion(this.Escritorio);
    //frmVtaFactura = new FrmVta_Factura(this.Escritorio);
    }
IfLogin objIFrame1=new IfLogin();




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMLogo = new javax.swing.JMenu();
        jMInicio = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jMRecHum = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        jMFinanciero = new javax.swing.JMenu();
        jMCompras = new javax.swing.JMenu();
        jMVentas = new javax.swing.JMenu();
        jMVta_Cliente = new javax.swing.JMenuItem();
        jMVta_Oferta = new javax.swing.JMenuItem();
        jMVta_Promocion = new javax.swing.JMenuItem();
        jMVta_Factura = new javax.swing.JMenuItem();
        jMVta_Garantias = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMvta_FormaPago = new javax.swing.JMenuItem();
        jMVta_Comision = new javax.swing.JMenuItem();
        jMInventario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(102, 255, 102));
        Escritorio.setToolTipText("");

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jMLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ups/edu/rrhh/menuinicio/logo-ups-home.png"))); // NOI18N
        jMenuBar1.add(jMLogo);

        jMInicio.setForeground(new java.awt.Color(0, 0, 102));
        jMInicio.setText("ProduEntrega S.A.");
        jMInicio.setBorderPainted(true);
        jMInicio.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N
        jMInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Inicio de Sesión");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMInicio.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("Cerrar Sesión");
        jCheckBoxMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem5ActionPerformed(evt);
            }
        });
        jMInicio.add(jCheckBoxMenuItem5);

        jMenuBar1.add(jMInicio);

        jMRecHum.setForeground(new java.awt.Color(0, 0, 102));
        jMRecHum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rh.gif"))); // NOI18N
        jMRecHum.setText("RRHH");
        jMRecHum.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Agregar Personal");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMRecHum.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Rol de Pago");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMRecHum.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("Vacaciones");
        jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        jMRecHum.add(jCheckBoxMenuItem4);

        jCheckBoxMenuItem6.setSelected(true);
        jCheckBoxMenuItem6.setText("Entrada & Salida");
        jCheckBoxMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem6ActionPerformed(evt);
            }
        });
        jMRecHum.add(jCheckBoxMenuItem6);

        jMenuBar1.add(jMRecHum);

        jMFinanciero.setForeground(new java.awt.Color(0, 0, 102));
        jMFinanciero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/finanzas.jpg"))); // NOI18N
        jMFinanciero.setText("Financiero");
        jMFinanciero.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        jMenuBar1.add(jMFinanciero);

        jMCompras.setForeground(new java.awt.Color(0, 0, 102));
        jMCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/compras.png"))); // NOI18N
        jMCompras.setText("Compras");
        jMCompras.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N
        jMenuBar1.add(jMCompras);

        jMVentas.setForeground(new java.awt.Color(0, 0, 102));
        jMVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ventas.jpg"))); // NOI18N
        jMVentas.setText("Ventas");
        jMVentas.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N

        jMVta_Cliente.setText("Cliente");
        jMVta_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVta_ClienteActionPerformed(evt);
            }
        });
        jMVentas.add(jMVta_Cliente);

        jMVta_Oferta.setText("Oferta");
        jMVta_Oferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVta_OfertaActionPerformed(evt);
            }
        });
        jMVentas.add(jMVta_Oferta);

        jMVta_Promocion.setText("Promocion");
        jMVta_Promocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVta_PromocionActionPerformed(evt);
            }
        });
        jMVentas.add(jMVta_Promocion);

        jMVta_Factura.setText("Factura");
        jMVta_Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVta_FacturaActionPerformed(evt);
            }
        });
        jMVentas.add(jMVta_Factura);

        jMVta_Garantias.setText("Garantias");
        jMVta_Garantias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVta_GarantiasActionPerformed(evt);
            }
        });
        jMVentas.add(jMVta_Garantias);

        jMenu1.setText("Pago");

        jMvta_FormaPago.setText("Formas Pago");
        jMvta_FormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMvta_FormaPagoActionPerformed(evt);
            }
        });
        jMenu1.add(jMvta_FormaPago);

        jMVta_Comision.setText("Comision");
        jMVta_Comision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVta_ComisionActionPerformed(evt);
            }
        });
        jMenu1.add(jMVta_Comision);

        jMVentas.add(jMenu1);

        jMenuBar1.add(jMVentas);

        jMInventario.setForeground(new java.awt.Color(0, 0, 102));
        jMInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/inventario.png"))); // NOI18N
        jMInventario.setText("Inventario");
        jMInventario.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N

        jMenuItem1.setText("Consultas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMInventario.add(jMenuItem1);

        jMenuItem2.setText("Reporte Ingreso");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMInventario.add(jMenuItem2);

        jMenuItem3.setText("Reporte Egreso");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMInventario.add(jMenuItem3);

        jMenuBar1.add(jMInventario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
                
       if(objIFrame1.isShowing())
	{
	    JOptionPane.showMessageDialog(null,"LA VENTANA YA ESTA ABIERTA");
        }
	else
	{
                Escritorio.add(objIFrame1);
                objIFrame1.setLocation(500, 80);
                objIFrame1.show();
                jMFinanciero.setVisible(false);
                jMRecHum.setVisible(false);
                jMCompras.setVisible(false);
                jMVentas.setVisible(false);
                jMInventario.setVisible(false);
   }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        try {
            IfDatos objIFrame2=new IfDatos();
            Escritorio.add(objIFrame2);
            objIFrame2.setLocation(280, 10);
            objIFrame2.show();
        } catch (SQLException ex) {
            Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jMVta_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVta_ClienteActionPerformed
        if(!frmVtaCliente.isShowing()){
            Escritorio.add(frmVtaCliente);
            frmVtaCliente.setLocation(280, 10);;
            frmVtaCliente.show();
        }
    }//GEN-LAST:event_jMVta_ClienteActionPerformed

    private void jMVta_FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVta_FacturaActionPerformed
        if(frmVtaFactura==null){
            frmVtaFactura = new FrmVta_Factura(Escritorio);
        }
        if(!frmVtaFactura.isShowing()){
            Escritorio.add(frmVtaFactura);
            frmVtaFactura.setLocation(280, 10);;
            frmVtaFactura.show();
        }
    }//GEN-LAST:event_jMVta_FacturaActionPerformed

    private void jMVta_OfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVta_OfertaActionPerformed
        if(!frmVtaOferta.isShowing()){
            Escritorio.add(frmVtaOferta);
            frmVtaOferta.setLocation(280, 10);
            frmVtaOferta.show();
        }
    }//GEN-LAST:event_jMVta_OfertaActionPerformed

    private void jMVta_PromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVta_PromocionActionPerformed
        if(!frmVtaPromocion.isShowing()){
            Escritorio.add(frmVtaPromocion);
            frmVtaPromocion.setLocation(280, 10);
            frmVtaPromocion.show();
        }
    }//GEN-LAST:event_jMVta_PromocionActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        try {
            IfRol objIFrame3=new IfRol();
            Escritorio.add(objIFrame3);
            objIFrame3.setLocation(450, 10);
            objIFrame3.show();
        } catch (SQLException ex) {
            Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
        IfVacaciones objIFrame4=new IfVacaciones();
        Escritorio.add(objIFrame4);
        objIFrame4.setLocation(450, 10);
        objIFrame4.show();
    }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

    private void jMvta_FormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMvta_FormaPagoActionPerformed
        if(frmVtaPago==null){
            frmVtaPago = new FrmVta_FormaPago();
        }
        if(!frmVtaPago.isShowing()){
            Escritorio.add(frmVtaPago);
            frmVtaPago.setLocation(280, 10);;
            frmVtaPago.show();
        }
    }//GEN-LAST:event_jMvta_FormaPagoActionPerformed

    private void jMVta_ComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVta_ComisionActionPerformed
        if(frmVtaComisones==null){
            frmVtaComisones = new FrmVta_Comisiones();
        }
        if(!frmVtaComisones.isShowing()){
            Escritorio.add(frmVtaComisones);
            frmVtaComisones.setLocation(280, 10);;
            frmVtaComisones.show();
        }
    }//GEN-LAST:event_jMVta_ComisionActionPerformed

    private void jMVta_GarantiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVta_GarantiasActionPerformed
        if(frmVtaGarantia==null){
            frmVtaGarantia = new FrmVta_Garantias();
        }
        if(!frmVtaGarantia.isShowing()){
            Escritorio.add(frmVtaGarantia);
            frmVtaGarantia.setLocation(280, 10);;
            frmVtaGarantia.show();
        }
    }//GEN-LAST:event_jMVta_GarantiasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
try {
            Principal1 Inventario = new Principal1();
            Escritorio.add(Inventario);
            Inventario.setLocation(280, 10);
            Inventario.show();
        } catch (Exception ex) {
            Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
           String dir = "C:\\Users\\anthony\\Documents\\NetBeansProjects\\UPS\\SI2Proyecto\\src\\Inventario_Reportes\\Reporte_ingreso.jrxml";
              JasperReport reporteJasper;
         
               reporteJasper = JasperCompileManager.compileReport(dir);
     
              JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null,conn);
              JasperViewer visor = new JasperViewer(mostrarReporte,false);
              visor.setVisible(true);  
              } catch (JRException ex) {
                  
       }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jCheckBoxMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem5ActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jCheckBoxMenuItem5ActionPerformed

    private void jCheckBoxMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem6ActionPerformed
        try {
            // TODO add your handling code here:
            IfRegistro objIFrame5=new IfRegistro();
            Escritorio.add(objIFrame5);
            objIFrame5.setLocation(450, 10);
            objIFrame5.show();
        } catch (SQLException ex) {
            Logger.getLogger(MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      try {
           String dir = "C:\\Users\\anthony\\Documents\\NetBeansProjects\\UPS\\SI2Proyecto\\src\\Inventario_Reportes\\Reporte_egreso.jrxml";
              JasperReport reporteJasper;
         
               reporteJasper = JasperCompileManager.compileReport(dir);
     
              JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null,conn);
              JasperViewer visor = new JasperViewer(mostrarReporte,false);
              visor.setVisible(true);  
              } catch (JRException ex) {
                  
       }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenuInicio().setVisible(true);
                MenuInicio men = new MenuInicio();
                men.setExtendedState(MAXIMIZED_BOTH);
                
                men.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    public static javax.swing.JMenu jMCompras;
    public static javax.swing.JMenu jMFinanciero;
    private javax.swing.JMenu jMInicio;
    public static javax.swing.JMenu jMInventario;
    private javax.swing.JMenu jMLogo;
    public static javax.swing.JMenu jMRecHum;
    public static javax.swing.JMenu jMVentas;
    private javax.swing.JMenuItem jMVta_Cliente;
    private javax.swing.JMenuItem jMVta_Comision;
    private javax.swing.JMenuItem jMVta_Factura;
    private javax.swing.JMenuItem jMVta_Garantias;
    private javax.swing.JMenuItem jMVta_Oferta;
    private javax.swing.JMenuItem jMVta_Promocion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMvta_FormaPago;
    // End of variables declaration//GEN-END:variables
}
